# Generated by Django 6.0.6 on 2026-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
